### PR TITLE
TuesPechkin.Wkhtmltox.AnyCPU

### PR DESCRIPTION
**Pull request by jonny64bit**
Added TuesPechkin.Wkhtmltox.AnyCPU which loads the respective resource dll
from a reference.

This should fix issue #87

Let me know any tweaks needed

### CODE REVIEW

**Comment by jonny64bit** [comment]
Just a quick heads up I just found out that this doesn't work for asp.net applications as asp.net loads all assembly's from the bin directory on app start. Shame cos it works nice for other application types. We are probably going to have to include wkhtmltox_32.dll.gz & wkhtmltox_64.dll.gz in the AnyCpu project and not reference the other two dlls.

**Comment by jonny64bit** [comment]
I've updated this to reflect these changes

**Comment by AndersRisager** [comment]
Hi Jonny

Nice Work ; )

I have exactly this problem at the moment. My Workstation is 64bit, but server is 32bit, so it will only work locally.

As I understand, you have fixed it, and also fixed the bug in Asp.Net Projects, so are you just waiting for it to be accepted?

Best regards
Anders

**Comment by jonny64bit** [comment]
@AndersRisager Yes, just waiting for it to be accepted.

**Comment by tuespetre** [comment]
Thanks for your work @jonny64bit! :smile: 

I will be getting around to this sometime soon. The busyness of life and so forth. :8ball:

**Comment by AndersRisager** [comment]
Great, andt thx for the quick response.

Btw. I compared it to the product from Winnovative and TuesPechkin.Wkhtmltox rendered standard HTML with twitter bootstrap (no pictures) slightly better but most importantly created much smaller pdf files. When Winnowative created a file around 200 kb, TuesPechkin.Wkhtmltox created the same file at around 66kb. That is a significant difference.

Heads up for the all the great Work.

**Comment by tuespetre** [comment]
@AndersRisager that is a 'thank you' to give to the https://github.com/wkhtmltopdf/wkhtmltopdf team. All I did was take someone else's .NET project and fix a bug!

**Comment by AndersRisager** [comment]
@tuespetre Well, that is true, but i would not be using their Work if it wasn't for your changes to it. Btw. i must admin that jonny64bit's changes really looks good :)

**Comment by hvidgaard** [comment]
Any progress on this? It's the single dependency that prevent my solution from being AnyCPU compatible for a majority of projects.

**Comment by jonny64bit** [comment]
I've had the anycpu version working in production without any problems for about a month now.

@hvidgaard You could just build the pull request version to it gets put into the main branch.

**Comment by AndersRisager** [comment]
@jonny64bit That is a nice workaorund ; ) Unfortunantly my department manager will only accept that we use third party products that are released... If that wasn't the case, i would not hesitate to use it like you describe. So i was forced to find another solution than Wkhtmltox.

**Comment by TWhidden** [comment]
Thanks Jonny - I was hoping the maintainer would accept the pull request sooner, and get a nuget package out, but just forked yours instead, and replaced the DLLs. worked fine that way.

**Comment by jonny64bit** [comment]
@tuespetre any chance we can get this accepted?

**Comment by fortboise** [comment]
Let me just comment in hopes that it might save someone else the trouble -- the asp.net problem noted back in February 2016 required me to use the TempFolderDeployment to make this work within Visual Studio 2015, .NET 4.5, etc. A note to that effect in the top level documentation (and accepting this branch) would be good. If your installation needs "AnyCPU" it likely needs TempFolderDeployment too. [Apologies if this is not the time or place - I'm new to github, and this is my first write to it.]

**Comment by tuespetre** [comment]
I did finally start merging this the other day (with the newest wkhtmltox to boot) but was getting `AccessViolationExceptions`. Sorry it took so long; I thought I was even going to need this project again but ended up not needing it still. I won't have time to work on this any more, I would be glad to work with someone on transferring ownership if desired.

**Pull request closed without merging**
