### PR TITLE
Table of content that works  :)

### PR DESCRIPTION
**Pull request by matma**
Table of content is the crucial feature for me.
So after digging in the wkhtmltopdf source, I understood the process of creating ToC. Table of content has it's own object settings, and it need to be first on the list of objects. Corresponding C code from wkhtmltopdf [examples](https://gist.github.com/matma/e5c5841324a13900c629#file-pdf_c_api-c-L74-L78).

This commit contains  "wkhtmltopdf 0.12.2" (I think it works better), some minor cleanups and whole new TableOfContentSettings. It behaves almost like in original "wkhtmltopdf" - there's an object of type TableOfContentSettings which triggers table of content creation. If there's no Xslt Transformation given, Pechkin is creating a new one like in "[wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/src/lib/tocstylesheet.cc)".

Test application now produces PDF document with table of content.

### CODE REVIEW

**Comment by wladpaiva** [comment]
@tuespetre have you ever implemented the TOC on the current version?

**Comment by tuespetre** [comment]
No; though part of what I set out to achieve with the 2.x.x family of releases was the ability for users to write their own `IDocument` and `ISettings` implementations with the `WkhtmltoxAttribute`, so they could write classes that only has the properties they need, or write classes that use properties/features that the class bundled with TuesPechkin do not support.

**Comment by wladpaiva** [comment]
Thats cool. Do you have any idea of how to implement that scenario of @matma?

``` c#
    Objects = {
        new ObjectSettings { HtmlText = "Front Cover" }, //should not go to ToC
        new TableOfContentSettings(),
        new ObjectSettings { HtmlText = "Content" },
        new ObjectSettings { HtmlText = "Last Page" }
    }
```

**Comment by wladpaiva** [comment]
Nevermind... I just copied the @matma classes and work fine.

**Comment by dalton478** [comment]
@wladiston with the new updates to TuesPechkin in 2.0 you can just take the TableOfContentsSettings (subclass ObjectSettings though) from @matma and stub or modify the XSL property. This will give you TOC support in whichever order you need in the doc. I can provide sample classes if needed.

@tuespetre I used suggested static converter with 2.0 release. I wanted to modify XSL for TOC but since StandardConverter.Toolset is protected I did not have direct access to the path of temp files. I did:

```
    public static RemotingToolset<PdfToolset> PdfToolset = new RemotingToolset<PdfToolset>(new Win32EmbeddedDeployment(new TempFolderDeployment()));
    public static IConverter PdfConverter = new ThreadSafeConverter(Static.PdfToolset);
```

and was able to get to the temp path via Static.PdfToolset.Deployment.Path

More importantly, the TOC would only come up on the first pdf of app lifecycle and never again, although the rest of the doc would come up. Through some research I concluded some settings on the toolset were being persisted across documents. Once I added a call to "Static.PdfToolset.Unload();" after each call to "Static.PdfConverter.Convert(document);" the TOC rendered each time without fail.

**Comment by NickOnbekend** [comment]
How can i use the TOC of @matma inside TuesPechkin version 2.1.1? @dalton478 you said "I can provide sample classes if needed." can you pls?

**Comment by dalton478** [comment]
I'm not very familiar with github options. Will post the classes as comments.

This is the TOC class:
using System;
using TuesPechkin;

namespace TuesPechkin {
    [Serializable]
    public class TableOfContentsSettings : ObjectSettings {
        public TableOfContentsSettings() {
            this.ProduceTableOfContents = true;
        }

```
    [WkhtmltoxSetting("isTableOfContent")]
    internal bool ProduceTableOfContents { get; set; }

    [WkhtmltoxSetting("toc.captionText")]
    public string CaptionText { get; set; }

    [WkhtmltoxSetting("toc.fontScale")]
    public double? FontScale { get; set; }

    [WkhtmltoxSetting("toc.indentation")]
    public string Indentation { get; set; }

    [WkhtmltoxSetting("toc.backLinks")]
    public bool ProduceBackLinks { get; set; }

    [WkhtmltoxSetting("toc.forwardLinks")]
    public bool ProduceForwardLinks { get; set; }

    [WkhtmltoxSetting("toc.useDottedLines")]
    public bool UseDottedLines { get; set; }

    [WkhtmltoxSetting("tocXsl")]
    public string XslStyleSheet { get; set; }
}
```

}

**Comment by dalton478** [comment]
A small static class to ensure we don't have multiple objects in the lifecycle:

namespace MyProgram {
    public static class Static {
        public static RemotingToolset<PdfToolset> PdfToolset = new RemotingToolset<PdfToolset>(new Win32EmbeddedDeployment(new TempFolderDeployment()));
        public static IConverter PdfConverter = new ThreadSafeConverter(Static.PdfToolset);
    }
}

And our print to pdf general class that uses them:

protected byte[] PrintToPDF(List<string> htmlBlocks, int insertTOCBeforeIndex, UserAccess userAccess, string documentTitle, string headerTitle = "", int tocAlternateStyleNumber = 0) {
    var document = new HtmlToPdfDocument() {
        GlobalSettings = {
            ColorMode = GlobalSettings.DocumentColorMode.Color,
            Orientation = GlobalSettings.PaperOrientation.Portrait,
            OutputFormat = TuesPechkin.GlobalSettings.DocumentOutputFormat.PDF,
            DocumentTitle = documentTitle,
            PaperSize = PaperKind.Letter,
            ImageQuality = 600,
            ImageDPI = 300,
            Margins = {
                All = 0.8,
                Unit = TuesPechkin.Unit.Inches
            }
        }
    };

```
var footerSetting = new FooterSettings() {
    RightText = "Footer Description - Company Name",
    LeftText = userAccess.userAccount.CompanyName,
    FontName = "Calibri",
    FontSize = 11
};

var headerSetting = new HeaderSettings() {
    FontName = "Calibri",
    LeftText = headerTitle,
    RightText = "[page]",
    FontSize = 10
};

for (int i = 0; i < htmlBlocks.Count; ++i) {
    var objectSetting = new ObjectSettings() {
        WebSettings = {
            EnableJavascript = true,
            PrintBackground = true,
            LoadImages = true,
            EnablePlugins = true,
            PrintMediaType = true,
            EnableIntelligentShrinking = false
        },
        HeaderSettings = headerSetting,
        FooterSettings = footerSetting,
        HtmlText = htmlBlocks[i],
        ProduceExternalLinks = true
    };
    if (insertTOCBeforeIndex > i) objectSetting.IncludeInOutline = false;
    else if (insertTOCBeforeIndex == i) {
        var tocSettings = new TableOfContentsSettings() {
            WebSettings = {
                EnableJavascript = true,
                PrintBackground = true,
                LoadImages = true,
                EnablePlugins = true,
                PrintMediaType = true,
                EnableIntelligentShrinking = false
            },
            HeaderSettings = headerSetting,
            FooterSettings = footerSetting,
            ProduceExternalLinks = true,

            CaptionText = "Contents",
            IncludeInOutline = false,
            ProduceForwardLinks = true,
            UseDottedLines = true
        };
        if (tocAlternateStyleNumber > 0) {
            string styleFilePath = "";
            if (tocAlternateStyleNumber == 1) styleFilePath = new TOCAlternate1(tocSettings).MakeStyleFile();

            if (styleFilePath != "") tocSettings.XslStyleSheet = styleFilePath;
        }
        document.Objects.Add(tocSettings);
    }

    document.Objects.Add(objectSetting);
    //document.GlobalSettings.DumpOutline = Path.Combine(Static.PdfToolset.Deployment.Path, "outline.xml");
}
byte[] ret = Static.PdfConverter.Convert(document);
Static.PdfToolset.Unload();  // very important; this must be called after (or at least before) each call to Convert due to a bug in the underlying 3rd-party library that persists some settings across documents
return ret;
```

}  // PrintToPDF

**Comment by dalton478** [comment]
Lastly, this is a short whitepapaer I wrote for internal consumption. It is meant to introduce our newer techs to the Tuespechkin library. It is what I think I learned but I can't guarantee it is perfectly accurate:

Tuespechkin PDF Library Notes

1.
The Tuespechkin library for PDF conversions is a .Net wrapper class around the C++ implementation of the Wkhtmltopdf library, which itself is largely a wrapper around the Webkit html rendering library.

2.
The C++ library attaches attributes to a structure of objects that are sent en masse to a Converter object. The converter object translates html text into a PDF document using the Webkit rendering engine.

a.
The object structure can be determined from looking at our source code or more formally by studying the auto-generated documentation here.

b.
There are many more attributes available in the C++ wrappers than the Tuespechkin library has implemented. The C++ documentation here can be studied for all available options.

c.
If you find a C++ attribute you need:

i.
Download the Tuespechkin library from github and open the solution in Visual Studio.

ii.
Using the object structure as a guide, create classes that inherit from the Tuespechkin classes or implement IDocument, IObject, and/or ISettings as needed. The Tuespechkin github page provides a useful and concise rundown to help frame the methodology.

iii.
In the classes, add properties with Wkhtmltoxsetting attibutes, spelling out the C++ property you need in the attribute line. Set this property as needed, add the object to the document(IDocument) object structure, and pass that document to the Convert method.

iv.
An example of this can be seen with the TableOfContentsSettings class in the Safety solution.

3.
Objects like outlines and TOC are meant to only show up once in a document. The Tuespechkin library has a bug (as of 6/16/15) that persists some settings across document conversions.

a.
The bug is in the internal PdfToolset object that is required to be instantiated only once per product lifecycle.

b.
To avoid this bug we must call Static.PdfToolset.Unload() after (to clean up) or before (to be safe) every call to Static.PdfConverter.Convert(document).

c.Not doing so will normally be ok if you are not using TOC or outlines, but it will put the next PDF document the system generates at risk if it does use them.

**Comment by dkozul** [comment]
I am using TuesPechkin in web application and I can't do unload of toolset because it will cause other parallel request to fail. I need to use TOC and without unloading it will be blank except first time.
Do you have any solution for this? How to fix bug in PdfToolset that is mentioned in post before?
I tried everything and i can't get this working.
Can anybody help?

**Pull request closed without merging**
